-- creating data bases
-- CREATE DATABASE `dp_instance_2`;
-- CREATE DATABASE `dp_instance_3`;
-- CREATE DATABASE `dp_instance_4`;
-- CREATE DATABASE `dp_instance_5`;
-- CREATE DATABASE `dp_instance_6`;
-- CREATE DATABASE `dp_instance_7`;
-- CREATE DATABASE `dp_instance_8`;
-- CREATE DATABASE `dp_instance_9`;
-- CREATE DATABASE `dp_instance_10`;
-- creating tables
-- use `dp_instance_1`;
-- CREATE TABLE `clubs` (
--   `club_name` varchar(45) DEFAULT NULL,
--   `city` varchar(45) DEFAULT NULL,
--   `foundation_date` date DEFAULT NULL,
--   `club_id` int NOT NULL,
--   `province` varchar(45) DEFAULT NULL,
--   PRIMARY KEY (`club_id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
-- use `dp_instance_2`;
-- CREATE TABLE `clubs` (
--   `club_name` varchar(45) DEFAULT NULL,
--   `city` varchar(45) DEFAULT NULL,
--   `foundation_date` date DEFAULT NULL,
--   `club_id` int NOT NULL,
--   `province` varchar(45) DEFAULT NULL,
--   PRIMARY KEY (`club_id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
-- use `dp_instance_3`;
-- CREATE TABLE `clubs` (
--   `club_name` varchar(45) DEFAULT NULL,
--   `city` varchar(45) DEFAULT NULL,
--   `foundation_date` date DEFAULT NULL,
--   `club_id` int NOT NULL,
--   `province` varchar(45) DEFAULT NULL,
--   PRIMARY KEY (`club_id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
-- use `dp_instance_4`;
-- CREATE TABLE `clubs` (
--   `club_name` varchar(45) DEFAULT NULL,
--   `city` varchar(45) DEFAULT NULL,
--   `foundation_date` date DEFAULT NULL,
--   `club_id` int NOT NULL,
--   `province` varchar(45) DEFAULT NULL,
--   PRIMARY KEY (`club_id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
-- use `dp_instance_5`;
-- CREATE TABLE `clubs` (
--   `club_name` varchar(45) DEFAULT NULL,
--   `city` varchar(45) DEFAULT NULL,
--   `foundation_date` date DEFAULT NULL,
--   `club_id` int NOT NULL,
--   `province` varchar(45) DEFAULT NULL,
--   PRIMARY KEY (`club_id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
-- use `dp_instance_6`;
-- CREATE TABLE `clubs` (
--   `club_name` varchar(45) DEFAULT NULL,
--   `city` varchar(45) DEFAULT NULL,
--   `foundation_date` date DEFAULT NULL,
--   `club_id` int NOT NULL,
--   `province` varchar(45) DEFAULT NULL,
--   PRIMARY KEY (`club_id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
-- use `dp_instance_7`;
-- CREATE TABLE `clubs` (
--   `club_name` varchar(45) DEFAULT NULL,
--   `city` varchar(45) DEFAULT NULL,
--   `foundation_date` date DEFAULT NULL,
--   `club_id` int NOT NULL,
--   `province` varchar(45) DEFAULT NULL,
--   PRIMARY KEY (`club_id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
-- use `dp_instance_8`;
-- CREATE TABLE `clubs` (
--   `club_name` varchar(45) DEFAULT NULL,
--   `city` varchar(45) DEFAULT NULL,
--   `foundation_date` date DEFAULT NULL,
--   `club_id` int NOT NULL,
--   `province` varchar(45) DEFAULT NULL,
--   PRIMARY KEY (`club_id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
-- use `dp_instance_9`;
-- CREATE TABLE `clubs` (
--   `club_name` varchar(45) DEFAULT NULL,
--   `city` varchar(45) DEFAULT NULL,
--   `foundation_date` date DEFAULT NULL,
--   `club_id` int NOT NULL,
--   `province` varchar(45) DEFAULT NULL,
--   PRIMARY KEY (`club_id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
-- use `dp_instance_10`;
-- CREATE TABLE `clubs` (
--   `club_name` varchar(45) DEFAULT NULL,
--   `city` varchar(45) DEFAULT NULL,
--   `foundation_date` date DEFAULT NULL,
--   `club_id` int NOT NULL,
--   `province` varchar(45) DEFAULT NULL,
--   PRIMARY KEY (`club_id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- import data
-- using import vizadrd import csv file from this catalog


